apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-dep
spec:
  replicas: 2
  selector:
    matchLables:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
        - name: express-health
          image: miteshdevops/express-health-api:1.0
          ports:
            - contianerPort: 3000
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initalDelaySeconds: 15
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            intialDelaySeconds: 10
            periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: express-service
spec:
  selector:
    app: express
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000

